// Generated by gencpp from file ardrone_test/Drone_odo.msg
// DO NOT EDIT!


#ifndef ARDRONE_TEST_MESSAGE_DRONE_ODO_H
#define ARDRONE_TEST_MESSAGE_DRONE_ODO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_test
{
template <class ContainerAllocator>
struct Drone_odo_
{
  typedef Drone_odo_<ContainerAllocator> Type;

  Drone_odo_()
    : x(0)
    , y(0)  {
    }
  Drone_odo_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::ardrone_test::Drone_odo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_test::Drone_odo_<ContainerAllocator> const> ConstPtr;

}; // struct Drone_odo_

typedef ::ardrone_test::Drone_odo_<std::allocator<void> > Drone_odo;

typedef boost::shared_ptr< ::ardrone_test::Drone_odo > Drone_odoPtr;
typedef boost::shared_ptr< ::ardrone_test::Drone_odo const> Drone_odoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_test::Drone_odo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_test::Drone_odo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ardrone_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ardrone_test': ['/home/esteban/tum_simulator_ws/src/ardrone_test/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_test::Drone_odo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_test::Drone_odo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_test::Drone_odo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_test::Drone_odo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_test::Drone_odo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_test::Drone_odo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_test::Drone_odo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b834ede922a0fff22c43585c533b49f";
  }

  static const char* value(const ::ardrone_test::Drone_odo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b834ede922a0fffULL;
  static const uint64_t static_value2 = 0x22c43585c533b49fULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_test::Drone_odo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_test/Drone_odo";
  }

  static const char* value(const ::ardrone_test::Drone_odo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_test::Drone_odo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
";
  }

  static const char* value(const ::ardrone_test::Drone_odo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_test::Drone_odo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Drone_odo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_test::Drone_odo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_test::Drone_odo_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_TEST_MESSAGE_DRONE_ODO_H
